// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Breadcurmb: typeof import("./src/components/breadcurmb.vue")["default"];
    Editor: typeof import("./src/components/markdown/editor.vue")["default"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    Notification: typeof import("./src/components/notification.vue")["default"];
    PanButton: typeof import("./src/components/form/pan-button.vue")["default"];
    PanInput: typeof import("./src/components/form/pan-input.vue")["default"];
    PanLink: typeof import("./src/components/form/pan-link.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
