// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateList: typeof import('./../src/components/animateList.vue')['default']
    ArticleList: typeof import('./../src/components/articleList.vue')['default']
    CategoryBar: typeof import('./../src/components/categoryBar.vue')['default']
    Drawer: typeof import('./../src/components/drawer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FormPanButton: typeof import('./../src/components/form/pan-button.vue')['default']
    FormPanInput: typeof import('./../src/components/form/pan-input.vue')['default']
    FormPanLink: typeof import('./../src/components/form/pan-link.vue')['default']
    Loading: typeof import('./../src/components/loading/index.vue')['default']
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default']
    Navigation: typeof import('./../src/components/navigation.vue')['default']
    Notification: typeof import('./../src/components/notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WangEditorEditor: typeof import('./../src/components/wangEditor/editor.vue')['default']
  }
}
